CREATE DATABASE YoutubeClone
GO

USE YoutubeClone
GO

CREATE TABLE UserAccount(
	UserID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	UserName NVARCHAR(20) NOT NULL UNIQUE,
	Email NVARCHAR(255) NOT NULL UNIQUE,
	DisplayName NVARCHAR (50) NOT NULL,
	Birthday DATETIME2 NOT NULL,
	Location NVARCHAR(30) NOT NULL,
	Password NVARCHAR(40) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	DeletedAt DATETIME2 NULL,
);
GO

CREATE TABLE Channel(
	ChannelID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	UserID UNIQUEIDENTIFIER NOT NULL REFERENCES UserAccount(UserID),
	Handle NVARCHAR (20) NOT NULL UNIQUE,
	DisplayName NVARCHAR(50) NOT NULL,
	Verification BIT NOT NULL DEFAULT 0,
	Description NVARCHAR(255) NULL,
	AvatarURL NVARCHAR(255) NULL,
	BannerURL NVARCHAR(255) NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	DeletedAt DATETIME2 NULL,
);
GO

CREATE TABLE VideoAccessibility(
	VideoAccessibilityID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DisplayName NVARCHAR(30) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
);
GO

INSERT INTO VideoAccessibility
	(DisplayName)
VALUES
	('Public'),
	('Private'),
	('Unlisted');
GO

CREATE TABLE Video(
	VideoID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	ChannelID UNIQUEIDENTIFIER NOT NULL REFERENCES Channel(ChannelID),
	VideoAccessibilityID INT NOT NULL REFERENCES VideoAccessibility(VideoAccessibilityID),
	Title NVARCHAR(255) NOT NULL,
	Description NVARCHAR(255) NULL,
	DurationSeconds INT NOT NULL,
	ThumbnailURL NVARCHAR(255) NOT NULL,
	AgeRestriction BIT NOT NULL DEFAULT 0,
	PublishedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	DeletedAt DATETIME2 NULL,
);
GO

CREATE TABLE Subscription(
	SubscriptionID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	UserID UNIQUEIDENTIFIER NOT NULL REFERENCES UserAccount(UserID),
	ChannelID UNIQUEIDENTIFIER NOT NULL REFERENCES Channel(ChannelID),
	VideoID UNIQUEIDENTIFIER NOT NULL REFERENCES Video(VideoID),
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	DeletedAt DATETIME2 NULL,
);
GO

CREATE TABLE ViewHistory(
	ViewHistoryID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	UserID UNIQUEIDENTIFIER NOT NULL REFERENCES UserAccount(UserID),
	VideoID UNIQUEIDENTIFIER NOT NULL REFERENCES Video(VideoID),
	CompletionRate DECIMAL NOT NULL DEFAULT 0.0,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
);
GO

CREATE TABLE Tag(
	TagID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	DisplayName NVARCHAR(20) NOT NULL,
);
GO

CREATE TABLE ReactionType(
	ReactionTypeID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	DisplayName NVARCHAR(20) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
);
GO

INSERT INTO ReactionType
	(DisplayName)
VALUES
	('Like'),
	('Dislike');
GO

CREATE TABLE VideoReaction(
	VideoReactionID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	VideoID UNIQUEIDENTIFIER NOT NULL REFERENCES Video(VideoID),
	UserID UNIQUEIDENTIFIER NOT NULL REFERENCES UserAccount(UserID),
	ReactionTypeID INT NOT NULL REFERENCES ReactionType(ReactionTypeID),
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
);
GO

CREATE TABLE Comment(
	CommentID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	VideoID UNIQUEIDENTIFIER NOT NULL REFERENCES Video(VideoID),
	UserID UNIQUEIDENTIFIER NOT NULL REFERENCES UserAccount(UserID),
	Content NVARCHAR(255) NOT NULL,
	IsPinned BIT NOT NULL DEFAULT 0,
	ParentCommentID UNIQUEIDENTIFIER NULL REFERENCES Comment(CommentID),
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	DeletedAt DATETIME2 NULL,
);
GO

CREATE TABLE CreatorType(
	CreatorTypeID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	DisplayName NVARCHAR(30) NOT NULL,
	ParentCommentID UNIQUEIDENTIFIER NULL REFERENCES Comment(CommentID),
);
GO

INSERT INTO CreatorType
	(DisplayName)
VALUES
	('UserAccount'),
	('Channel');
GO

CREATE TABLE Playlist(
	PlaylistID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	CreatorTypeID INT NOT NULL REFERENCES CreatorType(CreatorTypeID),
	UserID UNIQUEIDENTIFIER NOT NULL REFERENCES UserAccount(UserID),
	ChannelID UNIQUEIDENTIFIER NULL REFERENCES Channel(ChannelID),
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
);
GO

CREATE TABLE VideoTags(
	VideoID UNIQUEIDENTIFIER NOT NULL REFERENCES Video(VideoID),
	TagID UNIQUEIDENTIFIER NOT NULL REFERENCES Tag(TagID),
	CONSTRAINT PK_VideoTags_VideoID_TagID PRIMARY KEY (VideoID, TagID)
);
GO

CREATE TABLE PlaylistVideos(
	PlaylistID UNIQUEIDENTIFIER NOT NULL REFERENCES Playlist(PlaylistID),
	VideoID UNIQUEIDENTIFIER NOT NULL REFERENCES Video(VideoID),
	CONSTRAINT PK_PlaylistVideos_PlaylistID_VideoID PRIMARY KEY (PlaylistID, VideoID),
);
GO